export const MACHINE_SET_INITIAL = 'MACHINE_SET_INITIAL';
export const MACHINE_SET_ERROR = 'MACHINE_SET_ERROR';
export const MACHINE_PROCEED = 'MACHINE_PROCEED';

export const SELL_PRODUCT = 'SELL_PRODUCT';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const INSERT_MONEY = 'INSERT_MONEY';
